config/routes.rb
Rails.application.routes.draw do
  resources :ads
  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: %i[ show edit update destroy ]

  # GET /ads or /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1 or /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads or /ads.json
  def create
    @ad = Ad.new(ad_params)
    @ad.user_id = current_user.id

    respond_to do |format|
      if @ad.save
        format.html { redirect_to ad_url(@ad), notice: "Ad was successfully created." }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1 or /ads/1.json
  def update
    @ad.user_id = current_user.id
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to ad_url(@ad), notice: "Ad was successfully updated." }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1 or /ads/1.json
  def destroy
    @ad.destroy

    respond_to do |format|
      format.html { redirect_to ads_url, notice: "Ad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ad_params
      params.require(:ad).permit(:title, :desc, :price, :location, :category_id)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/views/ads/_ad.html.erb
<div class="col s12 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title">Title:-<%= ad.title %></span>
      <p>
        <strong>Description:</strong>
        <%= ad.desc %>
      </p>
      <% if params[:action]=="show" %>
        <p>
          <strong>Price:</strong>
          <%= ad.price %>
        </p>
        <p>
          <strong>Location:</strong>
          <%= ad.location %>
        </p>
        <p>
          <strong>User Mail</strong>
          <%= ad.user.email %>
        </p>
        <p>
          <strong>Category:</strong>
          <%=link_to "#{ad.category.title }", ad.category,class:"link-tag" %>
        </p>
      <%end%>
    </div>
    <div class="card-action">
      <% if params[:action]=="show"%>
        <%= link_to "Edit", edit_ad_path(ad) %>
        <%= link_to "Delete", ad, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn red dark-8" %>

      <%else%>
        <%= link_to "show", ad%>
      <%end%>
    </div>
  </div>
</div>

app/views/ads/_form.html.erb
<%= form_with(model: ad) do |form| %>
  <% if ad.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
        <% ad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field col s12">
     
      <%= form.text_field :title %>
       <%= form.label :title, style: "display: block active", class:"validate" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= form.text_area :desc , class:"materialize-textarea"%>
      <%= form.label :desc %>
    </div>
  </div>



  <div class="row">
    <div class="input-field col s12">
      <%= form.number_field :price , class:"validate"%>
      <%= form.label :price %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= form.text_area :location , class:"materialize-textarea"%>
      <%= form.label :location %>
    </div>
  </div>


  <div class="row">
    <%#= form.label :category_id, style: "display: block" %>

    <%= form.collection_select :category_id, Category.all, :id, :title, {prompt: "Choose a category"}, class:"browser-default" %>

    <%#= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit class:"btn large"%>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing ad</h1>

<%= render "form", ad: @ad %>

<br>

<div>
  <%= link_to "Show this ad", @ad %> |
  <%= link_to "Back to ads", ads_path %>
</div>

app/views/ads/index.html.erb
<h1>Ads</h1>
<div id="ads">
  <div class="container-fluid">
    <div class="row">
      <% @ads.each do |ad| %>
        <%= render ad %>
      <% end %>
    </div>
  </div>
</div>

app/views/ads/new.html.erb
<h1>New ad</h1>

<%= render "form", ad: @ad %>

<br>

<div>
  <%= link_to "Back to ads", ads_path %>
</div>

app/views/ads/show.html.erb
<%= render @ad %>