config/routes.rb
Rails.application.routes.draw do
  resources :ads
  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_alert.html.erb
<% if notice%>
    <p class="notice card-panel teal lighten-2 messages"><%= notice %></p>
<% end%>
<% if alert %>
    <p class="alert card-panel red dark-2 messages"><%= alert %></p>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2023 Rentopedia
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "New category", new_category_path %></li>
  <li><%= link_to "New ad", new_ad_path %></li>
  <li class="divider"></li>
  <li><a href="#">three</a></li>
</ul>

<ul id="dropdown2" class="dropdown-content">
  <li><%= link_to "New category", new_category_path %></li>
  <li><%= link_to "New ad", new_ad_path %></li>
  <li class="divider"></li>
  <li><a href="#">three</a></li>
</ul>


<ul class="sidenav" id="mobile-demo">
  <li><a href="sass.html">Category</a></li>
  <li><a href="badges.html">Ads</a></li>
  <li><a class="dropdown-trigger" href="#" data-target="dropdown2">List<i class="material-icons right">arrow_drop_down</i></a></li>
</ul>


<nav>
  <header class="nav-wrapper">
    <a href="<%= root_path %>" class="brand-logo">Rentopedia</a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <!--<li>
        <%#= link_to root_path do%>
          <i class="large material-icons">home</i>
        <#%end%>-->
      </li>
      <li>
        <%=link_to '<i class="large material-icons">home</i>'.html_safe, root_path %>
      </li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-trigger" href="#" data-target="dropdown1">List<i class="material-icons right">arrow_drop_down</i></a></li>
      <%= navlink%>
    </ul>
  </header>
</nav>