config/routes.rb
Rails.application.routes.draw do
  resources :ads
  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :ads
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    @category.user_id = current_user
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :desc)
    end
    def correct_user
      category = Category.find(params[:id])
      unless category.user == current_user
        redirect_to categories_url, alert: "You are not authorize for this action"
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%if params[:action]=='index' %>
<div class="col s10 m6 ">
<%else%>
<div class="container">
<%end%>
  <div style="width:500px;" class="card s3">
    <div class="card-image waves-effect waves-block waves-light">
      <%= image_tag 'default', class:"activator" %>
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4"><%= category.title %><i class="material-icons right">more_vert</i></span>
      <% if params[:action]=='index'%>
        <p><%= link_to "open", category %></p>
      <%end%>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Title:- <%= category.title %> <i class="material-icons right">close</i></span>
      <p>Description:- <%= category.desc %></p>
      <% if params[:action]=='show'%>
        <%= link_to "Edit", edit_category_path(category), class:"btn " %> |
        <%= link_to :back, categories_path, class:"btn blue lighten-1"%>  |
          <%= link_to "Delete", category, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn red dark-8" %>
      <%end%>
    </div>
  </div>
</div>


<!--
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= category.desc %>
  </p>

  <p>
    <strong>User Mail:</strong>
    <%= category.user.email %>
  </p>

</div>-->

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field col s12">
     
      <%= form.text_field :title %>
       <%= form.label :title, style: "display: block active", class:"validate" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= form.text_area :desc , class:"materialize-textarea"%>
      <%= form.label :desc %>
    </div>
  </div>

  <div class="row">
    <%= form.submit class:"btn blue" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<h1 class="card-panel  cyan darken-3 center-align" >Categories</h1>

<div id="categories">
  <div class="container-fluid">
    <div class="row">
      <% @categories.each do |category| %>
        <%= render category %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div class="row" >
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <%= render @category %>
</div>